name: Shared workflow

on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY_TOOLS:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Init - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Tools - checkout
        uses: actions/checkout@v3
        with:
          repository: "vegarringdal/action2"
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_TOOLS }}
          path: tools

      - name: Echo response
        working-directory: ./tools
        run: node test

      - name: Echo response
        run: echo Someone called for me? ${{inputs.config}}