name: Shared workflow

on:
  workflow_call:
    inputs:
      config:
        required: true
        type: string
    secrets:
      TEST1:
        required: true


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Init - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Tools - checkout
        uses: actions/checkout@v3
        with:
          ref: ${{github.ref_name}}
          path: tools

      - name: Echo response
        working-directory: ./tools
        run: node test

      - name: Echo response
        run: echo Someone called for me? ${{inputs.config}}